# ==========================================
# PIPELINE CI/CD para Node.js + React (Vite) -> Deploy a Azure App Service
# Proyecto: pwa-sistema-logistico
# ==========================================

trigger:
  branches:
    include:
      - dev
      - main

pool:
  vmImage: ubuntu-latest

stages:
# ======================
# 1️⃣ BUILD STAGE
# ======================
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js 20'

    - script: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v

        echo "--- Cleaning npm cache and node_modules ---"
        npm cache clean --force
        rm -rf node_modules

        echo "--- Installing dependencies ---"
        npm ci

        echo "--- Running build ---"
        npm run build
      displayName: 'Clean, Install Dependencies and Build App'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# ======================
# 2️⃣ TEST STAGE
# ======================
- stage: Test
  dependsOn: Build
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js 20 (for Test)'

    - script: |
        echo "--- No test script found in package.json ---"
        echo "--- Skipping tests ---"
      displayName: 'Skip Tests (No test configuration)'

# ======================
# 3️⃣ DEPLOY STAGE to Azure App Service
# ======================
- stage: Deploy
  dependsOn: Test
  condition: succeeded()
  displayName: 'Deploy Stage to Azure App Service'
  jobs:
  - deployment: DeployWeb
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)/app'
            displayName: 'Download Build Artifacts for Deployment'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service (staging)'
            inputs:
              azureSubscription: 'AzureAllenareConnection'
              appType: 'webAppLinux'
              appName: 'allenare'
              package: '$(System.ArtifactsDirectory)/app/drop'

          - task: AzureCLI@2
            displayName: 'Close Deployed Work Items (31, 33, 36)'
            condition: succeeded()
            inputs:
              azureSubscription: 'AzureAllenareConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              addSpnToEnvironment: true
              inlineScript: |
                echo "Closing specified Work Items after successful deployment..."
                WORK_ITEM_IDS_TO_CLOSE=(31 33 36)
                TARGET_STATE="Closed"
                for WORK_ITEM_ID in "${WORK_ITEM_IDS_TO_CLOSE[@]}"; do
                  echo "Updating Work Item ID: $WORK_ITEM_ID to state '$TARGET_STATE'"
                  az boards work-item update --id $WORK_ITEM_ID --state "$TARGET_STATE" --org "$(System.TeamFoundationCollectionUri)" --project "$(System.TeamProject)" || echo "Warning: Failed to update work item $WORK_ITEM_ID."
                done
                echo "Finished closing work items."

# ======================
# 4️⃣ MONITOR STAGE
# ======================
- stage: Monitor
  dependsOn: Deploy
  condition: succeeded()
  displayName: 'Monitor Stage'
  jobs:
  - job: MonitorJob
    steps:
    - script: |
        echo "--- Performing health check ---"
        curl -f -I https://allenare-fnfjg7crgyd7bqf9.canadacentral-01.azurewebsites.net || (echo "ERROR: Site unreachable or returned an error status" && exit 1)
        echo "Health check passed!"
      displayName: 'Check Deployment Health'
